### ISSUE TITLE
Build fails: Missing component

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-web-wallet#3]
On `3b9bd71` build fails, with the below error: 
 
````
ng build

Date: 2018-07-24T16:10:10.277Z
Hash: 2bd0e938a2655b437886
Time: 4896ms
chunk {main} main.js, main.js.map (main) 626 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 681 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 141 kB [initial] [rendered]

ERROR in src/app/app.module.ts(27,36): error TS2307: Cannot find module './tx-list-all/tx-list-all.component'.
````

**Comment by lehnberg** [comment]
If you reset to `41b3065` it builds properly and the wallet seems to be working okay, so it's the last  commit that introduced it.

**Comment by yeastplume** [comment]
Just missing files that I've pushed up now.. this is all very WIP stuff at the moment :D but if you get it going very happy to hear any feedback

**Comment by lehnberg** [comment]
Yeah I figured as much! 🙂

I got it working by resetting to the previous commit `41b3065` as it doesn't have all the tx-list references. Looks really good! Haven't tried sending coins using the interface yet. Let me know if there's anything in particular you want me to check out or input on: I assume the UI is still in flux and so it doesn't make a lot of sense to comment on that just yet?
